name: Fetch new data and build

on:
  schedule:
    # Run every 15 mins during specific hours (UTC)
    - cron: '*/15 4-20 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
      - name: Build the site
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python current_data.py
      - name: Install Netlify CLI
        run: npm install netlify-cli --location=global
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_PAT: ${{ secrets.NETLIFY_PAT }}
        run: |
          netlify deploy --prod \
          --dir ./build/ \
          --site $NETLIFY_SITE_ID \
          --auth $NETLIFY_PAT \
          --timeout 60 \
          --message "Site deployed at $(date)"
